version: '3'
services:
  sketch-ws:
    image: lpineda/sketch-ws:v4
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${PWD}/config.yml:/data/config.yml
    depends_on:
      - redis
      - mosquitto
    links:
      - redis
      - mosquitto
  redis:
    image: redis
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  sketch-ui:
    image: lpineda/sketch-ui:v4
    ports:
      - "80:80"
    links:
      - sketch-ws
    depends_on:
      - sketch-ws
