{
 "title": "Sketch-ws Dashboard 2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Processed events per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "processed_events_per_second", "legendFormat": "Events per second" }
   ]
  },
  {
   "title": "Detected Heavy Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "detected_heavy_hitters_per_epoch",
     "legendFormat": "HeavyHitters"
    },
    {
     "expr": "detected_heavy_changers_per_epoch",
     "legendFormat": "HeavyChangers"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_waiting_count", "legendFormat": "Threads waiting count" },
    { "expr": "jvm_threads_deadlock_count", "legendFormat": "Threads deadlock count" },
    { "expr": "jvm_threads_count", "legendFormat": "Threads count" }
   ]
  },
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_heap_used", "legendFormat": "Heap used" },
    { "expr": "jvm_memory_non_heap_used", "legendFormat": "Nonheap used" }
   ]
  },
  {
   "title": "Broker clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "Connected clients" },
    { "expr": "broker_clients_disconnected", "legendFormat": "Disconnected clients" },
    { "expr": "broker_clients_expired", "legendFormat": "Expired clients" }
   ]
  },
  {
   "title": "Broker received messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "broker_load_messages_received_1min",
     "legendFormat": "Received messages 1m"
    },
    {
     "expr": "broker_load_messages_received_5min",
     "legendFormat": "Received messages 5m"
    },
    {
     "expr": "broker_load_messages_received_15min",
     "legendFormat": "Received messages 15m"
    }
   ]
  }
 ]
}